# Generated by Django 5.2.17 on 2026-09-21 23:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_currency'),
        ('inventory', '0002_inventory_inventory_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_key', models.CharField(max_length=255, unique=True)),
                ('plan_type', models.CharField(choices=[('STANDARD', 'Standard Caisse & Stock (1 Poste)'), ('PRO', 'Professionnel Multi-Caisses (3 Postes)'), ('ENTERPRISE', 'Entreprise Illimitée & BI Analytics')], default='PRO', max_length=50)),
                ('max_registers', models.PositiveIntegerField(default=3)),
                ('issued_to_name', models.CharField(max_length=255)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('expires_at', models.DateField()),
                ('signature_hash', models.CharField(max_length=255)),
                ('is_revoked', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='inventory.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
