# Generated by Django 5.2.17 on 2026-09-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='inventory_type',
            field=models.CharField(choices=[('FULL', 'Inventaire complet'), ('PARTIAL', 'Inventaire tournant / partiel')], default='FULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('PURCHASE', 'Achat / Réception'), ('SALE', 'Vente'), ('RETURN_CUSTOMER', 'Retour client'), ('RETURN_SUPPLIER', 'Retour fournisseur'), ('TRANSFER_IN', 'Transfert entrant'), ('TRANSFER_OUT', 'Transfert sortant'), ('ADJUSTMENT_IN', 'Ajustement positif'), ('ADJUSTMENT_OUT', 'Ajustement négatif'), ('LOSS', 'Perte'), ('DAMAGE', 'Casse / Dépréciation'), ('INITIAL', 'Stock initial')], max_length=30),
        ),
    ]
