# Generated by Django 5.2.17 on 2026-09-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_inventory_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.TextField(blank=True, default='', help_text='Image logo du magasin encodée en Base64 ou URL'),
        ),
    ]
