# Generated by Django 5.2.17 on 2026-09-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_store_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklevel',
            options={'ordering': ['store', 'product'], 'verbose_name': 'Niveau de stock', 'verbose_name_plural': 'Niveaux de stock'},
        ),
    ]
