# Generated by Django 5.2.17 on 2026-09-19 16:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('trigger_type', models.CharField(choices=[('STOCK_BELOW_THRESHOLD', 'Stock inférieur au seuil d alerte'), ('OVERDUE_INVOICE', 'Facture ou créance impayée depuis X jours'), ('LARGE_TRANSACTION', 'Vente dépassant un montant cible'), ('INVENTORY_DISCREPANCY', 'Écart important constaté en inventaire')], max_length=50)),
                ('action_type', models.CharField(choices=[('CREATE_NOTIFICATION', 'Créer une notification utilisateur'), ('DRAFT_PURCHASE_ORDER', 'Générer un bon de commande fournisseur brouillon'), ('SEND_EMAIL_ALERT', 'Envoyer une alerte par e-mail'), ('LOG_AUDIT_WARNING', 'Consigner un avertissement dans le journal d audit')], max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text="Paramètres de configuration de la condition (ex: {'threshold': 5, 'days_overdue': 15})")),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
            ],
            options={
                'verbose_name': "Règle d'Automatisation",
                'verbose_name_plural': "Règles d'Automatisation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='companies.company')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='ai_assistant.automationrule')),
            ],
            options={
                'verbose_name': "Journal d'Exécution Règle",
                'verbose_name_plural': "Journaux d'Exécution Règles",
                'ordering': ['-executed_at'],
            },
        ),
    ]
