# Generated by Django 5.2.17 on 2026-09-28 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['name'], 'verbose_name': 'Caisse', 'verbose_name_plural': 'Caisses'},
        ),
    ]
